### ISSUE TITLE
EPERM, operation not permitted 'C:\zzz.ts-compiler.ts'

### ISSUE THREAD

**Issue by gb96** [meteor-typescript/meteor-typescript-compiler#25]
Running tsc version 1.0.3.0 and Meteor 1.1.0.2 on Windows 7.

File zzz.ts-compiler.ts is created in the project directory, but for some reason it is trying to write another on the root of the C:\ drive, and this fails due to my Windows security settings.

```javascript
=> Started proxy.
Could not find tsc binary, defaulting to 'tsc'.
=> Started MongoDB.
=> Errors prevented startup:

   While building the application:
   fs.js:439:18: EPERM, operation not permitted 'C:\zzz.ts-compiler.ts' (compiling zzz.ts-compiler.ts)
   at Object.fs.openSync (fs.js:439:18)
   at Object.fs.writeFileSync (fs.js:978:15)
   at checkForPlaceholderFile (packages/compileTypescript/plugin/compile-tsc.js:279:1)
   at handleSourceFile (packages/compileTypescript/plugin/compile-tsc.js:91:1)
   at arch (packages/compileTypescript/plugin/compile-tsc.js:68:1)


=> Your application has errors. Waiting for file change.
```

**Comment by gb96** [comment]
If I use Wndows Administrator privilege to copy zzz.ts-compiler.ts from the project root to C:\ then everything is happy and there are no errors.  The compiler does not attempt to write or rewrite 'C:\zzz.ts-compiler.ts'

**Comment by dalcib** [comment]
The same with me. 

Meteor 1.1.0.2 on Windows 8.1.

**Comment by tgienger** [comment]
After copying zzz.ts-compiler.ts from project root to C:\ I get the following error:

    While building the application:
       C:\Users\...\project\node_modules\zzz.ts-compiler.ts:1:1:
       module.js:338
       throw err;
       ^
       Error: Cannot find module 'C:\Users\...\project\node_modules\typescript\bin\tsc'
       at Function.Module._resolveFilename (module.js:336:15)
       at Function.Module._load (module.js:278:25)
       at Function.Module.runMain (module.js:501:10)
       at startup (node.js:129:16)
       at node.js:814:3

**Comment by shadyendless** [comment]
This seems strange that it is trying to write it to your C:\ drive. What is the path to everyone's projects?

@tgienger - the error you are getting now should be fixed in the latest version (assuming you are using the Visual Studio TypeScript plugin).

**Comment by gb96** [comment]
@shadyendless my project is located in ```"C:\Users\greg\Documents\git\glimmer"```

I just did a `meteor update` and got the latest versions:
```
    meteortypescript:compiler         upgraded from 2.0.8 to 2.0.9
    meteortypescript:typescript-libs  upgraded from 1.1.6 to 1.1.8
```

Note a couple of line numbers have now changed slightly in my stack-trace:

```javascript
   While building the application:
   fs.js:439:18: EPERM, operation not permitted 'C:\zzz.ts-compiler.ts' (compiling both/typescript-demo.ts)
   at Object.fs.openSync (fs.js:439:18)
   at Object.fs.writeFileSync (fs.js:978:15)
   at checkForPlaceholderFile (packages/compileTypescript/plugin/compile-tsc.js:280:1)
   at handleSourceFile (packages/compileTypescript/plugin/compile-tsc.js:92:1)
   at arch (packages/compileTypescript/plugin/compile-tsc.js:69:1)
```

**Comment by orefalo** [comment]
Seems to be coming from this line

compile-tsc.js:278

	var curPath = (!compileStep || compileStep.rootOutputPath == '/') ? PLACEHOLDER_FILENAME : compileStep.rootOutputPath.substr(1) + "/" + PLACEHOLDER_FILENAME;


most likely, this guy .. compileStep.rootOutputPath.substr(1)
   I wonder what it would look like on your system.

I don’t run windows - hard to debug

**Comment by shadyendless** [comment]
Fixed this. Making a pull request shortly.

**Comment by orefalo** [comment]
yep, the issue is…

you didn’t get my latest changes before doing your pull req. it was based off 2.0.8 when the latest is 2.0.9

as a consequence, it’s a little more work to merge your code.

**Comment by gb96** [comment]
I updated to 2.0.10.  No longer get the error about C:\ but nothing will compile now.  See sample error output below.

```
[[[[[ C:\Users\greg\Documents\git\glimmer ]]]]]

=> Started proxy.
=> Started MongoDB.

Compiling TypeScript os () files...

Compiling TypeScript web.browser () files...
=> Errors prevented startup:
   
   While building the application:
   C:\Users\greg\Documents\git\glimmer\zzz.ts-compiler.ts:1:1: 

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,27):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,36):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,46):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,55):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,63):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,64):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,66):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,74):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,75):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,77):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,85):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,86):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,88):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,95):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,108):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(18,115):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,27):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,36):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,46):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,55):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,63):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,64):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,66):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,74):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,75):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,77):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,85):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(21,86):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(194,20):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(194,28):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(194,29):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(195,21):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(195,29):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(195,30):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(196,22):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(196,30):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(196,31):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(197,26):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(197,34):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(197,35):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(331,44):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(403,31):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(437,29):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(439,47):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(439,54):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(443,43):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(443,50):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(444,51):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(444,58):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(444,78):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(445,43):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(445,50):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(446,51):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(446,58):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(446,78):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(484,22):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(484,31):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(528,42):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(638,18):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(638,26):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(638,27):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(678,45):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(678,54):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(678,64):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(678,83):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(680,45):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(681,52):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(705,17):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(705,25):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(705,26):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(706,18):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(706,26):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(706,27):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(707,19):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(707,27):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(707,28):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(708,23):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(708,31):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(708,32):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(724,46):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(755,28):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(755,36):
   error TS1005: '=' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(757,29):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(757,37):
   error TS1005: '=' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(758,27):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(758,35):
   error TS1005: '=' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(762,37):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(762,45):
   error TS1005: '=' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\meteor.d.ts(794,30):
   error TS1005: ';' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\ironrouter.d.ts(80,56):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\ironrouter.d.ts(80,92):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(279,59):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(279,73):
   error TS1005: '=' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(279,76):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(298,41):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(298,63):
   error TS1005: '=' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(298,117):
   error TS1005: '>' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(298,139):
   error TS1005: '=' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(298,147):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(315,56):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(315,78):
   error TS1005: '=' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(315,140):
   error TS1005: '>' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(315,162):
   error TS1005: '=' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(315,170):
   error TS1003: Identifier expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(322,50):
   error TS1005: ',' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(322,72):
   error TS1005: '=' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(322,127):
   error TS1005: '>' expected.

   C:\Users\greg\Documents\git\glimmer\.meteor\local\build\programs\server\assets\packages\meteortypescript_typescript-libs\definitions\jquery.d.ts(322,149):
   error TS1005: '=' expected.

```

**Comment by shadyendless** [comment]
You need to upgrade your version of TypeScript. Upgrade it to the 1.5.0 beta and your issue will go away (this package requires it to be at at least 1.4 to work).

**Comment by gb96** [comment]
Looks like I'm using 1.5.0.0 Beta already.  Removed older versions just in case, but still getting the same errors.

**Comment by shadyendless** [comment]
When you type `tsc --version` in the console, what do you get? You should get: 

`message TS6029: Version 1.5.0-beta`

Also, navigate to the following directory on your computer: `C:\Program Files (x86)\Microsoft SDKs\TypeScript`, if there are any folders in there besides 1.5, delete them.

**Comment by gb96** [comment]
Yes, I get the version message exactly as you said.  And I had also already removed all other TypeScript folders besides 1.5.

If I roll back to ```meteortypescript:compiler@2.0.9``` and create ```C:\zzz.ts-compiler.ts`` it all compiles fine.  So seems to be a regression bug with 2.0.10.  My guess is 2.0.10 is not finding ```zzz.ts-compiler.ts``` at all now.

**Comment by shadyendless** [comment]
It doesn't ever try to "find" it, necessarily. It just creates the file in the root directory of your project (or at least that's the intention it seems). I tested this locally by creating a project in my Documents folder (which is how I also fixed the plugin). I'm quite unsure at this point how to go about fixing your issue >.>

The error messages you said you got when you were on 2.0.10 are the some ones I get if I try to use an older version of TypeScript.

**Comment by gb96** [comment]
Ok, I put some garbage text inside ```project-root\zzz.ts-compiler.ts``` and so compilation failed.
Then I deleted ```project-root\zzz.ts-compiler.ts``` and let tsc recreate it.

Now the project compiles and runs fine.  Not sure why, maybe the ```.meteor/local/build``` needed some kind of clean-out?

**Comment by gb96** [comment]
I also note that running `meteor reset` seems to break tsc on the next `meteor` build:

```
error TS6053: File
.meteor/local/build/programs/server/assets/packages/meteortypescript_typescript-libs/definitions/all-definitions.d.ts' not found.
```
But then it succeeds if you run `meteor` again.

**Comment by shadyendless** [comment]
Yeah, that's to be expected. The reason this happens is that when you do a `meteor reset`, it clears out all of the files it generated before (including those required by packages). So, when you run `meteor` again, it re-downloads the files for the packages, but unfortunately it does this at a strange point in the pipeline.

I'll look into the other project (the error you are mentioning is happening because the definition files aren't created until after `meteor` is run, which is creating a condition where your personal code is relying on something that doesn't exist yet and also why running `meteor` a second time fixes the issue).

**Comment by barbatus** [comment]
seems to be outdated, please check out the last version.
